--CUSTOMER BEHAVIOR ANALYSIS SQL QUERIES--





			SELECT* 
			FROM customer;

			
--Q1. What is the total revenue generated by male vs female customers?

		  SELECT 
			  gender,
			  SUM(purchase_amount) as revenue 
		  FROM  
		      customer
		 GROUP BY 
		      gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

		SELECT
			customer_id
		FROM  
		    customer
		WHERE purchase_amount>
			(SELECT  AVG(purchase_amount) FROM customer)
		AND	
			discount_applied = 'Yes';


-- Q3. Which are the top 5 products with the highest average review rating?

 	 SELECT
			item_purchased,
			AVG(review_rating) AS average_rating
	 FROM		 
	         customer
	GROUP BY  
	         item_purchased
    ORDER BY average_rating DESC
	LIMIT 5;		

			
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
			 
	 SELECT
		   shipping_type,
		   ROUND (AVG(purchase_amount),2)AS avg_purchase_amount
     FROM 
	       customer
     WHERE 
	       shipping_type ='Standard'
		               OR
		   shipping_type ='Express'
	 GROUP BY 
	       shipping_type
	ORDER BY 
	       avg_purchase_amount DESC;



--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.


		SELECT
		    COUNTcustomer_id) AS Total_customers,
		    subscription_status,
		    SUM(purchase_amount) AS Total_Revenue,
		    round(avg(purchase_amount),2) AS avg_spent
		FROM 
		    customer
		GROUP BY 
		    subscription_status
		ORDER BY 
		    total_revenue,avg_spent DESC;



-- -Q6. Which 5 products have the highest percentage of purchases with discounts
-- applied?


		SELECT 
		      item_purchased,
		      ROUND(COUNT(*) filter(WHERE discount_applied = 'Yes')*100.0/COUNT(*),2)
		                                AS  percent_of_purchases
		FROM 
		         customer 
	    GROUP BY 
		         item_purchased
	    ORDER BY 
		         percent_of_purchases DESC 
	  LIMIT 5;

		                   or

		SELECT 
		       item_purchased,
		       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
		FROM   
		       customer
		GROUP BY 
		       item_purchased
		ORDER BY 
		       discount_rate DESC
		LIMIT 5;

		
--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

			
				
				-- Step 1: Define customer segments
		WITH customer_segments AS (
		    SELECT 
		        customer_id,
		        CASE
		            WHEN previous_purchases = 1 THEN 'New'
		            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		            ELSE 'Loyal'
		        END AS customer_segment
		    FROM customer
		)
		
		-- Step 2: Aggregate customer counts per segment
		SELECT 
		    customer_segment,
		    COUNT(*) AS customer_count
		FROM customer_segments
		GROUP BY customer_segment
		ORDER BY customer_count DESC;


--Q8. What are the top 3 most purchased products within each category? 


		      SELECT * 
		       FROM
		        (SELECT 
		               category,
				       item_purchased,
				       COUNT(*) AS total_purchase,
				       ROW_NUMBER() OVER(
					       PARTITION BY  category 
					       ORDER BY COUNT(*)DESC
						   ) AS top3_rank_in_category
				      FROM 
				          customer
				      GROUP BY 
				          item_purchased,category) t
				      WHERE top3_rank_in_category<4;

		
			 
		 -- SELECT* FROM CUSTOMER;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

 		SELECT
		      subscription_status,
		      COUNT(customer_id) AS cust_count
		 FROM 
		     customer
		WHERE 
		     previous_purchases>5
		GROUP BY 
		     subscription_status;
		 
	
--Q10. What is the revenue contribution of each age group? 

		 SELECT
		       age_group,
			   SUM(purchase_amount) AS revenue
		FROM 
		     customer
		GROUP BY 
		     age_group
		ORDER BY
		     revenue desc;